import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E5E5E5",
  },
  logoImage: {
    width: 150,
    height: 150,
    marginTop: 10,
    // alignSelf:"center"
  },
  headerView: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
    paddingBottom: 20,
  },
  headerTxt: {
    color: "#F2F2F2",
    fontWeight: "bold",
    fontSize: 20,
  },
  linearGradient: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,

    elevation: 24,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
  },
  inputsView: {
    marginTop: 20,
  },
  input: {
    width: "82%",
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 30,
    padding: 7,
    paddingLeft: 15,
    borderColor: "#3CA874",
    color: "#656972",
    elevation: 5,
    backgroundColor: "#E5E5E5",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
  },
  passwordInputView: {
    width: "82%",
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 30,
    padding: 7,
    paddingLeft: 15,
    borderColor: "#3CA874",
    color: "grey",
    elevation: 5,
    backgroundColor: "#E5E5E5",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    display: "flex",
    flexDirection: "row",
    marginTop: 15,
  },
  passwordInput: {
    width: "88%",
    color: "#656972",
  },
  txt1: {
    textAlign: "center",
    marginTop: 20,
    color: "#2C2E33",
  },
  btn1: {
    width: "80%",
    alignSelf: "center",
    padding: 20,
    borderRadius: 30,
    marginTop: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  txt2: {
    textAlign: "center",
    color: "#2C2E33",
    fontWeight: "bold",
  },
  socialBtnView: {
    marginTop: 20,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    width: "80%",
    borderBottomWidth: 1,
    borderBottomColor: "green",
    alignSelf: "center",
    paddingBottom: 30,
  },
  socialBtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#656972",
    padding: 10,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
    backgroundColor: "#E5E5E5",
    width: "40%",
  },
  txt6: {
    color: "#525068",
    marginLeft: 3,
    fontWeight: "bold",
  },
  txt3: {
    color: "#1877F2",
    marginLeft: 3,
    fontWeight: "bold",
  },
  txt4: {
    textAlign: "center",
    marginTop: 30,
  },
  txt5: {
    textAlign: "center",
    marginTop: 10,
  },
});
export default styles;
